# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

inhibit_all_warnings!

def import_pods
  pod 'ICONKit', :git => 'https://github.com/icon-project/ICONKit'
end

target 'Whollet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ICONKit', :git => 'https://github.com/icon-project/ICONKit'
  
  target 'WholletTests' do
    # Comment the next line if you don't want to use dynamic frameworks
    inherit! :search_paths
    use_frameworks!
    inherit! :search_paths  
    pod 'ICONKit', :git => 'https://github.com/icon-project/ICONKit'
  end
end
